name: fisherman_app
description: A new Flutter project for fishermen.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  provider: ^6.0.5
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^10.1.1
  flutter_svg: ^2.2.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true